// AUTH CONSTANTS

export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGOUT = 'LOGOUT';
export const WRONG_CREDENTIALS = 'WRONG_CREDENTIALS';
export const RESET_WRONG_CREDENTIALS = 'RESET_WRONG_CREDENTIALS';
export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";


export const STORE_CUSTOMERS = "STORE_CUSTOMERS"